

int main()
{
		try
		{
		
			throw exception;  
			 
		
		}
		
		catch
		{
			
			
			
		} 
		
		return 1; 
}



